# Generated by Django 5.2.1 on 2025-06-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scriptapp", "0003_project_proofreader_project_transcriber"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
