# Generated by Django 5.2.1 on 2025-06-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scriptapp", "0004_project_is_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcript",
            name="is_final",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="transcript",
            name="role",
            field=models.CharField(
                choices=[
                    ("transcriber", "Transcriber"),
                    ("proofreader", "Proofreader"),
                ],
                max_length=20,
            ),
        ),
    ]
