services:
  web:
    build: .
    command: gunicorn transcription.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8001:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env
    depends_on:
      - db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_volume:/var/lib/postgresql/data

volumes:
  db_volume:
  media_volume:
  static_volume:
